### ISSUE TITLE
What is your operating system?

### ISSUE THREAD

**Issue by jennybc** [jennybc/whattheyforgot-seattle#1]
Issue opened for use during What They Forgot to Teach You About R workshop in Seattle on October 4/5 2018

**Put an emoji reaction** on the relevant comment below to indicate which operating system you use.

**Comment by jennybc** [comment]
macOS Mojave – version 10.14

**Comment by jennybc** [comment]
macOS High Sierra – version 10.13

**Comment by jennybc** [comment]
macOS Sierra – version 10.12 or earlier

**Comment by adrisede** [comment]
CentOS, Windows10, Windows7, Ubuntu Linux

**Comment by michaellynnmorris** [comment]
Windows 10.

**Comment by snurpdurp** [comment]
Windows 10

**Comment by elliothershberg** [comment]
High Sierra

**Comment by anthonyatto** [comment]
high sierra 10.13 👍

**Comment by michaelbiafore** [comment]
Windows 10

**Comment by OO00OO00** [comment]
windows 10 🐱‍👓

**Comment by jennybc** [comment]
tabulated in main Happy Git repo
