### ISSUE TITLE
Office hours sign up

### ISSUE THREAD

**Issue by jennybc** [jennybc/whattheyforgot-seattle#2]
Location and link to Doodle sign up will appear here, in due course.

**Comment by apreshill** [comment]
Link to office hours sign up:

[http://bit.ly/wtf-seattle-2018](http://bit.ly/wtf-seattle-2018)

**Comment by jennybc** [comment]
It looks like the Westin lobby bar is a suitable place for us to hang around, with computers, with drinks and do this. So that's the plan.
